Task : Pansharpening


network :
  in_dim : 4
  feature_dim : 8
  y_dim : 1
  depth : 8
  ratio_spatial : 8
  ratio_freq : 2
  ratio_fusion : 1
  control_nums : 4
  middle_blk_num : 1
  enc_blk_nums : [1,1]
  dec_blk_nums : [1,1]
  u_transform: False



datasets :
  GF2:
    train: ["/mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/training_data/train_gf2.h5"] #4bands
    test_reduce: /mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/test_data/GF2/test_gf2_multiExm1.h5
    test_full: /mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/test_data/GF2/test_gf2_OrigScale_multiExm1.h5
    image_scale: 1023.0
  QB:
    train: ["/mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/training_data/train_qb.h5"] #4bands
    test_reduce: /mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/test_data/QB/test_qb_multiExm1.h5
    test_full: /mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/test_data/QB/test_qb_OrigScale_multiExm1.h5
    image_scale: 2047.0
  WV3:
    train: ["/mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/training_data/train_wv3.h5"] #8bands
    test_reduce: /mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/test_data/WV3/test_wv3_multiExm1.h5
    test_full: /mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/test_data/WV3/test_wv3_OrigScale_multiExm1.h5
    image_scale: 2047.0
  WV2:
    test_reduce: /mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/test_data/WV2/test_wv2_multiExm1.h5
    test_full: /mnt/hdd0/zhangcx/Dataset/Pancollection_Dataset/PanCollection/test_data/WV2/test_wv2_OrigScale_multiExm1.h5
    image_scale: 2047.0



train :
  batch_size : 32
  use_shuffle: true
  epoch : 1000
  clip_grad : true
  loss_type : mix3  #mix1\mix2\mse\Charbonnier

  load :
    inherit : True
    model : pansharpening_gf2.pth

  optim:
    type : AdamW #AdamW
    init_lr : !!float 1e-3
    weight_decay : !!float 1e-3
    final_lr : !!float 1e-4
    betas : [0.9,0.95]
    scheduler_type : linear #cosine

save:
  freq : 5000
  auto_freq : 50

val:
  RR_freq : 5000
  FR_freq : 5000