Task : NYU_depth_SR


network :
  in_dim : 1
  feature_dim : 16
  y_dim : 3
  depth : 6
  ratio_spatial : 32
  ratio_freq : 2
  ratio_fusion : 1
  control_nums : 4
  middle_blk_num : 4
  enc_blk_nums : [1,2]
  dec_blk_nums : [2,1]
  u_transform: True


datasets :
  train :
    path : "/mnt/hdd0/zhangcx/Dataset/NYUV2/train"
    patch_size : 128
    batch_size : 16
    aug_mode : True
    use_shuffle: true

  test :
    NYUv2: "/mnt/hdd0/zhangcx/Dataset/NYUV2/test"
    Middlebury: "/mnt/hdd0/zhangcx/Dataset/Middlebury"
    Lu:  "/mnt/hdd0/zhangcx/Dataset/Lu/"
    RGBDD: "/mnt/hdd0/zhangcx/Dataset/RGB-D-D"

scale : 8

train :
  epoch : 2000
  clip_grad : true
  loss_type : mix3  #mix1\mix2\mse\Charbonnier

  load :
    inherit : False
    model : gdsr_x8.pth

  optim:
    type : AdamW #AdamW
    init_lr : !!float 1e-4
    weight_decay : !!float 1e-3
    final_lr : !!float 1e-5
    betas : [0.9,0.95]
    scheduler_type : linear #cosine

save:
  freq : 5000
  auto_freq : 500

val:
  freq : 5000
